# Generated by Django 6.0.1 on 2026-01-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureone', '0002_userdeviceinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeviceInfo',
        ),
    ]
